### PR TITLE
feat: update Greenchoice API endpoint(s)

### PR DESCRIPTION
**Pull request by szamfirov**
## Details

There are a few new / changed API endpoints. Below you can find a screenshot with the working version.

* New endpoint called "/microbus/init" which gives everything customer related - accounts, profiles, active / inactive contracts etc.
* The rates / tariffs endpoint is completely different now - it's bound to customer contract details

## Screenshot after the changes

Screenshot 2024-08-30 at 14 19 58

### CODE REVIEW

**Comment by FlexxFR** [comment]
Not sure how I can use this as it;s not committed yet.
But, did you,by acciddent, also discovered a new rate concerning the "terugleververgoeding"? It should retrieve a value of € 0,11616.

**Comment by FlexxFR** [comment]
Okay, I added this repository to HACS, removed the "orginal" and installed this one.
The HTTP Error: 500 Server Error is indeed solved :), the integration loads and reapears in the HA integration overview.

However, there is still an error letting the integration "crash", no entities are created or added.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:727
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 20:09:25 (10 occurrences)
Last logged: 20:09:25

greenchoice: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 727, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/greenchoice/sensor.py", line 157, in update
    self._measurement_date = api_result[self._measurement_date_key]
                             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'measurement_date_electricity'

**Comment by szamfirov** [comment]
> Not sure how I can use this as it;s not committed yet. But, did you,by acciddent, also discovered a new rate concerning the "terugleververgoeding"? It should retrieve a value of € 0,11616.

I believe the API returns this as well but didn't prioritize this at all. I'm just after the usual "normaal", "dal" and gas prices because I'm tired of updating those numbers myself every time there's a change 😅 

PS: There are also a nice forecasting endpoint which shows incoming tariff changes for those with an "open" contract but I'm leaving this to those who are willing to take a stab at implementing something cool.

**Comment by szamfirov** [comment]
> greenchoice: Error on device update! Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 727, in _async_add_entity await entity.async_device_update(warning=False) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update await hass.async_add_executor_job(self.update) File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/greenchoice/sensor.py", line 157, in update self._measurement_date = api_result[self._measurement_date_key] ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'measurement_date_electricity'

I feel this might be some cache related issue - you might try removing the integration, restarting HA and then installing it again. I assume it's working fine for @barisdemirdelen now that the PR is merged.

**Comment by barisdemirdelen** [comment]
Indeed seems to be working for me, @szamfirov thank you for the api update!

**Comment by FlexxFR** [comment]
I'm sorry, but it is still not working for me.
I tried uninstalling/installing multiple times.

It does "something" as it uses some off my personal info in a URL request.

HTTP Error: 404 Client Error: Not Found for url: https://mijn.greenchoice.nl/api/v2/Rates/2177418?AgreementIdElectricity=2776016&AgreementIdGas=2776016&HouseNumber=&ReferenceIdElectricity=179687&ReferenceIdGas=&ZipCode=

When I browse to the URL directly:
{"type":"[https://tools.ietf.org/html/rfc9110#section-15.5.5","title":"Not](https://tools.ietf.org/html/rfc9110#section-15.5.5%22,%22title%22:%22Not) Found","status":404,"traceId":"00-8ae3c3ee9dd6ab574bf5fb6900a2f3fe-c5c3e1715bdc8eb6-00"}

**Pull request merged**
